//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelMaster.HeadOffice.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FuelMaster.HeadOffice.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic name must be at most 100 characters..
        /// </summary>
        public static string ArabicNameMaxLength {
            get {
                return ResourceManager.GetString("ArabicNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name is required..
        /// </summary>
        public static string ArabicNameRequired {
            get {
                return ResourceManager.GetString("ArabicNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign station to zone has no prices..
        /// </summary>
        public static string AssignStationToInitialZoneException {
            get {
                return ResourceManager.GetString("AssignStationToInitialZoneException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find this tank ! ..
        /// </summary>
        public static string CannotFindTank {
            get {
                return ResourceManager.GetString("CannotFindTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete entity related with other entities..
        /// </summary>
        public static string CantDelete {
            get {
                return ResourceManager.GetString("CantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password was wrong ..
        /// </summary>
        public static string CurrentPasswordWrong {
            get {
                return ResourceManager.GetString("CurrentPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee was not found..
        /// </summary>
        public static string EmployeeNotFound {
            get {
                return ResourceManager.GetString("EmployeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee is not in station of this transaction..
        /// </summary>
        public static string EmployeeNotInStation {
            get {
                return ResourceManager.GetString("EmployeeNotInStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic name must be at most 100 characters..
        /// </summary>
        public static string EnglishNameMaxLength {
            get {
                return ResourceManager.GetString("EnglishNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name is required..
        /// </summary>
        public static string EnglishNameRequired {
            get {
                return ResourceManager.GetString("EnglishNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity not found.
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login ..
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nozzle is disabled..
        /// </summary>
        public static string NozzleDisabled {
            get {
                return ResourceManager.GetString("NozzleDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nozzle was not found..
        /// </summary>
        public static string NozzleNotFound {
            get {
                return ResourceManager.GetString("NozzleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price should be greater than zero..
        /// </summary>
        public static string PriceShouldBeGreaterThanZero {
            get {
                return ResourceManager.GetString("PriceShouldBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, Connect with support to solve this problem..
        /// </summary>
        public static string SthWentWrong {
            get {
                return ResourceManager.GetString("SthWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tank has no fuel enough..
        /// </summary>
        public static string TankHasNoFuelEnough {
            get {
                return ResourceManager.GetString("TankHasNoFuelEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank has no free space to this opration  !.
        /// </summary>
        public static string TankHasNoSpace {
            get {
                return ResourceManager.GetString("TankHasNoSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to login at first !.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not exist ..
        /// </summary>
        public static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is used from another account ..
        /// </summary>
        public static string UserNameIsUsed {
            get {
                return ResourceManager.GetString("UserNameIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find prices in the stations zone..
        /// </summary>
        public static string ZonePricesNotFound {
            get {
                return ResourceManager.GetString("ZonePricesNotFound", resourceCulture);
            }
        }
    }
}
